global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'khedmti-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
          - 'host.docker.internal:8081'
          - 'host.docker.internal:8082'
          - 'host.docker.internal:8083'
